### ISSUE TITLE
Github Workflow before merge

### ISSUE THREAD

**Issue by FlynnOConnell** [LukeBrandon/leurocord#16]
-     Check if the code compiles: It can build with no compilation errors
-     Using rustfmt, check if the code is properly formatted
-     Using clippy, it can check for common mistakes and improvements

Separate checks for backend and frontend, might not want the clippy/rustfmt checks until we can config out the annoying style changes

**Comment by LukeBrandon** [comment]
@NeuroPyPy I think `fmt` and `clippy` is fine and actually good, the default configuration are pretty dang good and hold you accountable.  As far as formatting goes, the "standard rust formatting" should be the default for `fmt`
