### ISSUE TITLE
Create a secret with the connection string to the database

### ISSUE THREAD

**Issue by FlynnOConnell** [LukeBrandon/leurocord#19]
Something like: 

`postgresql://username:password@localhost/databasename`

and access with

`${{ secrets.DATABASE_URL }}`

_Originally posted by @NeuroPyPy in https://github.com/LukeBrandon/fluke/issues/17#issuecomment-1586493463_

**Comment by LukeBrandon** [comment]
@NeuroPyPy Are you talking about a Github Secret here? We probably won't need to worry about this until we have a deployed version, and even then I'm not sure we could deploy anything using a Github Secret?

**Comment by FlynnOConnell** [comment]
@LukeBrandon I think it needs to be an [environment variable](https://docs.rs/sqlx/latest/sqlx/macro.query.html#requirements)?
