### ISSUE TITLE
Setup local development environment (db, contiainer)

### ISSUE THREAD

**Issue by LukeBrandon** [LukeBrandon/leurocord#7]
`docker-compose`?
- For easy, one-line up and running stuff
- Should be all configured using environment variables
`postgresql`?
- `sqlx` will need to know who to talk to

**Comment by FlynnOConnell** [comment]
All of the query macros for sqlx require an active connection and `cargo build` fails without it, so you need to have an active database connection before you run the build - fine for now. Might think about hosting somewhere soon. I'm tired of docker run commands

**Comment by LukeBrandon** [comment]
Yea, requiring a connection to build is pretty lame, surely `sqlx` has a workaround for this, perhaps `cargo build --release` doesn't require DB to check against? @NeuroPyPy

**Comment by FlynnOConnell** [comment]
Nope that requires an active connection too, only option I can see is running sqlx in offline mode and running `cargo sqlx prepare` first, which makes a json file for the queries to read from.. but then we have to make sure either a .env file isn't passed or if it is, we set `SQLX_OFFLINE` to true @LukeBrandon
